Update java to 11
error:
java.lang.AssertionError: annotationType(): unrecognized Attribute name MODULE (class com.sun.tools.javac.util.UnsharedNameTable$NameImpl)

solution:
https://stackoverflow.com/questions/68344424/unrecognized-attribute-name-module-class-com-sun-tools-javac-util-sharednametab

This arises in Android builds from a combination of:

    Using compileSdkVersion 31 (or maybe later),
    With JDK8,
    Having any Lambda style related code somewhere (else error may not happen).

The default android toolchains have moved to JDK11 now, you must use JDK11, at least if you change any of the Android API target versions to 31 (or later).